# Generated by Django 5.2.6 on 2025-09-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorconfig',
            name='device_pruning_days',
            field=models.PositiveIntegerField(blank=True, default=180, help_text='Удалять устройства, которые не проявляли активность указанное количество дней. Оставьте пустым, чтобы отключить.', null=True, verbose_name='Удалять неактивные устройства (дней)'),
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='device_pruning_delete_logs',
            field=models.BooleanField(default=True, help_text='Если флажок снят, при удалении неактивного устройства его записи в журнале аудита будут сохранены (отвязаны от устройства).', verbose_name='Удалять связанные логи при удалении устройства'),
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='log_rotation_days',
            field=models.PositiveIntegerField(blank=True, default=90, help_text='Удалять записи журнала старше указанного количества дней. Оставьте пустым, чтобы отключить.', null=True, verbose_name='Хранить логи (дней)'),
        ),
        migrations.AddField(
            model_name='sensorconfig',
            name='log_rotation_max_count',
            field=models.PositiveIntegerField(blank=True, default=100000, help_text='Хранить только N самых последних записей в журнале. Оставьте пустым, чтобы отключить.', null=True, verbose_name='Хранить логов (макс. кол-во)'),
        ),
    ]
