# Generated by Django 5.2.6 on 2025-09-12 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensorconfig_device_pruning_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Метка времени'),
        ),
    ]
