# Generated by Django 5.2.6 on 2025-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-объект с HTTP-заголовками. Пример: {"Authorization": "Bearer key123"}', verbose_name='Заголовки'),
        ),
    ]
