# Generated by Django 5.2.6 on 2025-09-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_alter_webhook_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='coalesce_text_limit',
            field=models.PositiveIntegerField(default=8000, help_text='Максимальный размер (в символах) объединенного тела запроса. Если превышен, старые события могут быть отброшены.', verbose_name='Лимит текста для объединения'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='rate_limit_action',
            field=models.CharField(choices=[('QUEUE', 'Поставить в очередь и отправить позже'), ('COALESCE', 'Объединить и отправить позже')], default='QUEUE', max_length=10, verbose_name='Действие при ограничении'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='rate_limit_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Не отправлять чаще, чем раз в указанное количество секунд. 0 - отключено.', verbose_name='Период ограничения (секунд)'),
        ),
    ]
