# Generated by Django 5.2.7 on 2025-10-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0003_webhook_coalesce_text_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='JSON-объект с HTTP-заголовками. Пример: {"Authorization": "Bearer key123"}', null=True, verbose_name='Заголовки'),
        ),
    ]
