name: Build and Push Docker Image
permissions:
  contents: read

# Этот workflow запускается при каждом push в ветку 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu в качестве исполнителя

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Настройка QEMU для эмуляции CPU (хорошая практика для Buildx)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Шаг 3: Настройка Docker Buildx для более эффективной сборки
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Шаг 4: Вход в Docker Hub
      # Используются секреты, которые нужно предварительно настроить в репозитории GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 5: Сборка и публикация образа
      # Образ будет опубликован с двумя тегами: 'latest' и коротким хешем коммита
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: >
            linux/amd64,
            linux/arm64,
            linux/amd64/v2,
            linux/amd64/v3
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sensor-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/sensor-app:${{ github.sha }}
